### ISSUE TITLE
Ревью IndexPage

### ISSUE THREAD

**Issue by FilippovAM** [KADUSHKEVICH/test-project#1]
https://github.com/KADUSHKEVICH/test-project/blob/75060950dcbd39d68775ef3ab03d95fc1da6d596/src/pages/index.js#L9

Обрати внимание как добавляется класс:
className="App"
в то время как на страницах(/page-1, /page-2) 
<img width="657" alt="image" src="https://user-images.githubusercontent.com/12913535/180916748-87f25752-fcde-47c7-8b6e-3391d3da3758.png">

В чём разница?

**Comment by YanKadush** [comment]
Разница в том, что в одном случае я использую Name.module.css, а в другом просто Name.css файл для того, чтоб импортировать шрифт в одно место.

**Comment by FilippovAM** [comment]
Переделывать не нужно. Для инфо, 
<img width="930" alt="image" src="https://user-images.githubusercontent.com/12913535/184587514-ce02d91e-d7b3-425f-8b7d-a5dcd368df37.png">
Эта часть тоже тянет на css-модуль. 

При текущем import, в бандле сохраняются имена классов. Это не ошибка, но если выбрал один вариант написания кода, то лучше его придерживаться. Конкретно в этом случаи, не смысла сохранять имена классов для link/app.
