### ISSUE TITLE
Ревью List

### ISSUE THREAD

**Issue by FilippovAM** [KADUSHKEVICH/test-project#5]
https://github.com/KADUSHKEVICH/test-project/blob/75060950dcbd39d68775ef3ab03d95fc1da6d596/src/components/List/List.js#L4-L16

Для корректной/оптимальной работы рендера списка нужно использовать ключи. Ты правильно сделал что вынес данные в массив и отрендерил их списком. Но давай избавимся от key в данных в пользу использования index из метода .map
<img width="1050" alt="image" src="https://user-images.githubusercontent.com/12913535/180920357-46e668ac-29a7-4e63-974b-2dddb581f467.png">

<img width="1602" alt="image" src="https://user-images.githubusercontent.com/12913535/180920444-b2606224-3c1c-4744-807d-3fee8ec010dd.png">

**Comment by YanKadush** [comment]
Добавил key со значением index внутри метода map
