### ISSUE TITLE
Изменение макета

### ISSUE THREAD

**Issue by FilippovAM** [KADUSHKEVICH/test-project#7]
В макете не ярко выражен layout который мы хотим увидеть. Подкрутил макет.

Было:
<img width="1175" alt="image" src="https://user-images.githubusercontent.com/12913535/180922169-322f44c8-2815-4e0b-b122-b97aea9ea365.png">

Стало: 
<img width="860" alt="image" src="https://user-images.githubusercontent.com/12913535/180922255-ea3c670f-475c-4f80-8bf1-adf57fb51764.png">

Для мобилки layout не менялся.
Для десктопа, увеличили отступы у элементов списка. Обрати внимание как ведёт себя левый столбец.

**Comment by YanKadush** [comment]
Добавил определение ширины с использованием хуков и условный рендеринг компонента Comment (относительно брэйкпоинта 768px)
Залью в ближайшее время

**Comment by FilippovAM** [comment]
@KADUSHKEVICH сделал? Если да, можно закрывать issue. 
Несколько issue активны, есть вопросы по ним?
