### ISSUE TITLE
2 колонки описал как 8

### ISSUE THREAD

**Issue by FilippovAM** [KADUSHKEVICH/test-project#9]
Немного не разобрался в том как работает grid-template-area. Из макета видно что колонки 2. 

https://github.com/KADUSHKEVICH/test-project/blob/b556a78ce56cd9cc24bbc3a14ed79184ee2ed3a8/src/styles/page-1.module.css#L23

8 колонок: 
<img width="1184" alt="image" src="https://user-images.githubusercontent.com/12913535/184589113-96413fe9-e97a-4b71-b343-8497bce9b4e3.png">

2 колонки:
<img width="2060" alt="image" src="https://user-images.githubusercontent.com/12913535/184588854-e4e7db14-07d3-4efd-a7d7-973f87d998b3.png">
<img width="988" alt="image" src="https://user-images.githubusercontent.com/12913535/184588876-ceecc381-fb58-4bcc-8008-b3dacb4af282.png">

**Comment by YanKadush** [comment]
Я изначально сделал 2 колонки, они интуитивно туда встают, но потом, я обратил внимание что в макете Figma есть layout на 8 и 12 колонок. Решил что необходимо реализовать исходя из данных сеток, вот и переписал блок на repeat(8, 1fr). 

Энивэй, Спасибо за коммент)
